apiVersion: apps/v1
kind: Deployment
metadata:
  name: testjenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testjenkins
  template:
    metadata:
      labels:
        app: testjenkins
    spec:
      containers:
        - name: testjenkins
          image: 192.168.49.2:5000/testjenkins:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: testjenkins
spec:
  selector:
    app: testjenkins
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer