apiVersion: apps/v1
kind: Deployment
metadata:
  name: testjenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testjenkins
  template:
    metadata:
      labels:
        app: testjenkins
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: testjenkins
      containers:
        - name: testjenkins
          image: testjenkins:latest
          command: ["java"]
          args: ["-jar", "app.jar", "--spring.config.additional-location=file:///config2/", "--spring.profiles.active=dev", "--jasypt.encryptor.password=${JASYPT_ENCRYPTOR_PASSWORD}"]
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          volumeMounts:
            - name: config-volume
              mountPath: /config
              readOnly: false
          env:
            - name: PROPERTIES_PATH
              value: file:///config/
---
apiVersion: v1
kind: Service
metadata:
  name: testjenkins
spec:
  type: NodePort
  selector:
    app: testjenkins
  ports:
    - port: 8081
      targetPort: 8080
      protocol: TCP
      nodePort: 30001