apiVersion: apps/v1
kind: Deployment
metadata:
  name: testjenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testjenkins
  template:
    metadata:
      labels:
        app: testjenkins
    spec:
      containers:
        - name: testjenkins
          image: localhost:5000/testjenkins:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: testjenkins
spec:
  type: NodePort
  selector:
    app: testjenkins
  ports:
    - port: 8081
      targetPort: 8080
      protocol: TCP
      nodePort: 30001