spring.application.name=testjenkins
management.endpoints.web.exposure.include=refresh, env
greeting.template=Hola, %s!
app.password=123
show.properties.contains=app,greeting
app.propiedad.no.sobreescrita=Con tildes - áéíóú

spring.datasource.url=${DB_URI}
spring.datasource.username=${DB_USER_NAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update