apiVersion: v1
kind: ConfigMap
metadata:
  name: testjenkins
data:
  application.properties: |
    {{APPLICATION_PROPERTIES}}
    app.redis.password={{REDIS_PASSWORD}}
    app.password={{APP_PASSWORD}}
  messages.properties: |
    {{MESSAGES_PROPERTIES}}
  resilience-dev.yaml: |
    {{RESILIENCE_PROPERTIES}}